help("abs")
help("round")
help("tolower")
help("toupper")
abs(-15)
print(abs(-15))
round(4.483847, digits = 1)
species <- "SPECIES"
tolower(species)
toupper(species)
abs_value <- sqrt(2.6)
abs_rounded_value <- (round(abs_value, digits = 2))
print(abs_rounded_value)
print(round(sqrt(2.6), digits = 2))
